### ISSUE TITLE
Add a .gitattributes file to the repository

### ISSUE THREAD

**Issue by Costpap** [Suggester-Bot/Suggester#150]
Hello. After looking at the [.eslintrc.js](../blob/production/.eslintrc.js) configuration file, I noticed that all end-of-line (EOL) breaks should be in LF. This issue recommends the addition of a `.gitattributes` file to the repository, in order to allow for Git to automatically clone the files with LF line breaks, and more. I hope that this is taken into consideration, as it will make contributing to the repository on Windows systems that use CRLF EOLs way easier.

[Git Documentation on gitattributes](https://git-scm.com/docs/gitattributes)

---
Edit: Add link to Git Doc

**Comment by BrightnessTM** [comment]
If anyone would like to PR this, we'll be happy to merge it

**Comment by Costpap** [comment]
I would try to PR one myself, the only thing is that I don't want to mess up the line endings themselves.
